use crate::models::review::ReviewItem;

/// vault 知識庫指針受管區塊（adr-004 keystone：repo Layer-2 指針，路徑無關）。
/// `for_codex` 決定引用哪個全局錨點檔（Codex / Claude）。
/// `memory_bullets`：本專案記憶索引的條目（由 `memory_bullets()` 產生）。**內聯**而非僅指標——
/// 實測顯示薄指標不會被主動跟讀，內聯到必讀的 AGENTS.md/CLAUDE.md 才可靠。空字串 → 顯示「（尚無）」。
pub fn build_vault_pointer_block(vault_folder: &str, for_codex: bool, memory_bullets: &str) -> String {
    let anchor = if for_codex { "~/.codex/AGENTS.md" } else { "~/.claude/CLAUDE.md" };
    let mem = if memory_bullets.trim().is_empty() {
        "（尚無）".to_string()
    } else {
        memory_bullets.trim_end().to_string()
    };
    [
        "<!-- AMAGI-VAULT-PROJECT:BEGIN (Amagi Core 管理，勿手改) -->".to_string(),
        "## 知識庫指針".to_string(),
        format!("本專案知識庫：vault `{}/`（邏輯位置，非絕對路徑）。", vault_folder),
        "- 接任務前**先讀該處 `handoff.md`（當前狀態活頁，最新進度）**，再讀 `index.md`、`knowledge/`、近期 `reports/` 恢復脈絡。".to_string(),
        format!("- vault 根的本機路徑見全局指針（`{}` 的 AMAGI-VAULT 區塊）。", anchor),
        "- 產出規範/決策/規格/報告一律寫入該 vault 路徑（依 type 分流），不寫絕對機器路徑。".to_string(),
        String::new(),
        format!("### 本專案記憶（已內聯，開場即視為已知；需細節再讀 vault `{}/agent/memory/<檔>`）", vault_folder),
        mem,
        "<!-- AMAGI-VAULT-PROJECT:END -->".to_string(),
    ]
    .join("\n")
}

/// 專案根檔的「開發工作流薄錨」：doctrine 全文在全域（`~/.claude/CLAUDE.md`／`~/.codex/AGENTS.md`，
/// 開場自動載入），此處只宣告遵循 + 指出軌跡落點，避免每專案複製全文（漂移）。
/// 僅專案層帶；全域 CLAUDE.md（`build_claude_md(None, …)`）不帶（doctrine 本體已在全域）。
pub fn workflow_anchor_block() -> String {
    [
        "## 開發工作流（依全域 doctrine）",
        "本專案依「標準開發工作流」（全域 `~/.claude/CLAUDE.md`／`~/.codex/AGENTS.md`，開場自動載入）：先分析、制訂計畫 → 拆步驟、逐步執行、每步留證據、不跳步不併步 → 自我驗證（完成＝有客觀證據）→ 4.5 交叉審查（含完成度稽核）→ commit 預覽。",
        "步驟與結果軌跡寫入 `.amagi/workflow-state.md`（進行中），完成後歸檔 `.amagi/history/`。",
    ]
    .join("\n")
}

/// 專案層 AGENTS.md：含 vault 指針 + **內聯本專案記憶索引**（細節仍在 vault `agent/memory/`）+ 工作流薄錨。
pub fn build_agents_md(vault_folder: &str, memory_bullets: &str) -> String {
    [
        "# AGENTS.md".to_string(),
        String::new(),
        "> Auto-generated by AMAGI Core. Do not edit manually.".to_string(),
        String::new(),
        build_vault_pointer_block(vault_folder, true, memory_bullets),
        String::new(),
        workflow_anchor_block(),
        String::new(),
    ]
    .join("\n")
}

/// 專案層 CLAUDE.md：純薄指標。`vault_folder` 為 `Some` 時帶專案指針；
/// `None`（全域 ~/.claude/CLAUDE.md）不帶專案指針。
pub fn build_claude_md(vault_folder: Option<&str>, memory_bullets: &str) -> String {
    let mut lines = vec![
        "# CLAUDE.md".to_string(),
        String::new(),
        "> Auto-generated by AMAGI Core. Do not edit manually.".to_string(),
        String::new(),
    ];

    if let Some(vf) = vault_folder {
        lines.push(build_vault_pointer_block(vf, false, memory_bullets));
        lines.push(String::new());
        lines.push(workflow_anchor_block());
        lines.push(String::new());
    }

    lines.join("\n")
}

/// 單筆記憶檔（vault `agent/memory/<slug>.md`）：frontmatter + 內文。
/// `id:` 為穩定身分鍵（adr-005 / spec §5 最小版）：loader 優先以此為操作鍵，
/// 檔名的 `slug-<idfrag>` 僅作可讀性與一致性守門（idfrag = id 前 8 位英數）。
pub fn build_memory_file(item: &ReviewItem) -> String {
    // 顯示用日期取本地時區（created_at 以 UTC 儲存）：避免台北凌晨換算回 UTC 差一天（F3）。
    let created = item.created_at.with_timezone(&chrono::Local).format("%Y-%m-%d");
    let mut s = String::from("---\n");
    s.push_str(&format!("id: {}\n", item.id));
    s.push_str(&format!("title: \"{}\"\n", yaml_escape(&item.title)));
    s.push_str(&format!("category: {}\n", item.category));
    s.push_str(&format!("created: {}\n", created));
    s.push_str("---\n\n");
    s.push_str(item.content.trim());
    s.push('\n');
    s
}

/// 記憶索引 MEMORY.md：一行一筆（標題 — hook — 連結），由 agent/memory 目錄重建。
/// `entries`：(檔名, 標題, 一句 hook)。
pub fn build_memory_index(entries: &[(String, String, String)]) -> String {
    format!(
        "# 記憶索引\n\n> 一行一筆速查；需要細節讀對應檔。由 Amagi Core 自動重建。\n\n{}",
        memory_bullets(entries)
    )
}

/// 中和會破壞「受管區塊」邊界或 Markdown 連結的字元（Codex 高風險）。
/// 此索引會內聯進 AI 必讀的 CLAUDE.md/AGENTS.md，故須清洗 title/hook：
/// - 取單行（去換行）；中和 HTML comment delimiters（防注入 `<!-- AMAGI-VAULT:END -->` 假標記）。
/// `in_link_text`＝true 時另保護 `[` `]`（會提前關閉連結文字）。
pub fn sanitize_inline(s: &str, in_link_text: bool) -> String {
    let one_line = s.lines().next().unwrap_or("").trim();
    // 插入空白破壞 `<!--` / `-->`，使任何記憶內容都無法構成受管區塊標記（exact-match 失效）。
    let mut out = one_line.replace("<!--", "<! --").replace("-->", "-- >");
    if in_link_text {
        out = out.replace('[', "(").replace(']', ")");
    }
    out
}

/// 把記憶索引條目渲染成 Markdown 條列（一行一筆），供 MEMORY.md 與「內聯進錨點/指針」共用。
/// `entries`：(檔名, 標題, 一句 hook)。title/hook 經 `sanitize_inline` 清洗，杜絕 marker 注入。
pub fn memory_bullets(entries: &[(String, String, String)]) -> String {
    let mut s = String::new();
    for (file, title, hook) in entries {
        let t = sanitize_inline(title, true);
        if hook.is_empty() {
            s.push_str(&format!("- [{}]({})\n", t, file));
        } else {
            s.push_str(&format!("- [{}]({}) — {}\n", t, file, sanitize_inline(hook, false)));
        }
    }
    s
}

/// 產生 Claude / Codex 原生 Skills 格式（.claude/skills/<slug>/SKILL.md）。
/// frontmatter 帶 description 與 when_to_use，讓 Claude 原生自動觸發。
pub fn build_native_skill_md(item: &ReviewItem) -> String {
    let when_to_use = section_all_lines(&item.content, "何時使用");
    let desc_line = section_first_line(&item.content, "描述");

    // description：標題 + 描述首行（含觸發語意），供 Claude 判斷何時套用
    let description = match desc_line {
        Some(d) => format!("{}。{}", item.title, d),
        None => item.title.clone(),
    };

    let mut fm = String::from("---\n");
    fm.push_str(&format!("name: \"{}\"\n", yaml_escape(&item.title)));
    fm.push_str(&format!("description: \"{}\"\n", yaml_escape(&description)));
    if let Some(w) = when_to_use {
        fm.push_str(&format!("when_to_use: \"{}\"\n", yaml_escape(&w)));
    }
    fm.push_str("---\n\n");

    format!("{}# {}\n\n{}\n", fm, item.title, item.content)
}

/// 取某個 `## 段落` 的第一行非空內容（去掉清單符號）
fn section_first_line(content: &str, section: &str) -> Option<String> {
    let header = format!("## {}", section);
    let mut in_section = false;
    for line in content.lines() {
        let t = line.trim();
        if t.starts_with("## ") {
            in_section = t == header;
            continue;
        }
        if in_section && !t.is_empty() {
            let cleaned = t.trim_start_matches(['-', '*', ' ']).trim();
            if !cleaned.is_empty() {
                return Some(cleaned.to_string());
            }
        }
    }
    None
}

/// 取某個 `## 段落` 的所有非空行（去清單符號），用「；」串成一行
fn section_all_lines(content: &str, section: &str) -> Option<String> {
    let header = format!("## {}", section);
    let mut in_section = false;
    let mut parts: Vec<String> = Vec::new();
    for line in content.lines() {
        let t = line.trim();
        if t.starts_with("## ") {
            if in_section { break; }
            in_section = t == header;
            continue;
        }
        if in_section && !t.is_empty() {
            let cleaned = t.trim_start_matches(['-', '*', ' ']).trim();
            if !cleaned.is_empty() {
                parts.push(cleaned.to_string());
            }
        }
    }
    if parts.is_empty() { None } else { Some(parts.join("；")) }
}

/// YAML 雙引號字串轉義
fn yaml_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::review::*;
    use chrono::Utc;

    fn skill_item(title: &str, content: &str) -> ReviewItem {
        ReviewItem {
            id: "t".into(),
            project_id: "p".into(),
            item_type: ReviewItemType::Skill,
            category: "skill".into(),
            title: title.into(),
            content: content.into(),
            risk: RiskLevel::Low,
            status: ReviewStatus::Accepted,
            sync_targets: vec![],
            sync_scope: SyncScope::Project,
            source_pending_file: None,
            blocked_hits: vec![],
            created_at: Utc::now(),
            reviewed_at: None,
        }
    }

    #[test]
    fn test_native_skill_frontmatter() {
        let content = "## 描述\n做計算模組\n\n## 何時使用\n- 計算機\n- 觸發關鍵字：四則運算\n\n## 步驟\n1. 做";
        let out = build_native_skill_md(&skill_item("計算模組", content));
        assert!(out.starts_with("---\n"));
        assert!(out.contains("name: \"計算模組\""));
        assert!(out.contains("description: \"計算模組。做計算模組\""));
        // when_to_use 應含兩行串接
        assert!(out.contains("計算機；觸發關鍵字：四則運算"));
        // 內文保留
        assert!(out.contains("## 步驟"));
    }

    #[test]
    fn test_native_skill_no_sections() {
        let out = build_native_skill_md(&skill_item("純文字技能", "這只是一段說明"));
        assert!(out.contains("name: \"純文字技能\""));
        assert!(out.contains("description: \"純文字技能\""));
        assert!(!out.contains("when_to_use:")); // 無何時使用段落
    }

    #[test]
    fn test_vault_pointer_in_generated_files() {
        // 內聯記憶索引：帶入一筆 bullet，應出現在產出檔中
        let bullets = memory_bullets(&[(
            "test-mem.md".to_string(),
            "測試記憶".to_string(),
            "一句 hook".to_string(),
        )]);

        // AGENTS.md：含專案指針、保留標頭、引用 codex 錨點、內聯記憶索引
        let agents = build_agents_md("projects/foo", &bullets);
        assert!(agents.starts_with("# AGENTS.md"));
        assert!(agents.contains("AMAGI-VAULT-PROJECT:BEGIN"));
        assert!(agents.contains("projects/foo/"));
        assert!(agents.contains("~/.codex/AGENTS.md"));
        // 開場讀取須先讀 handoff.md（當前狀態活頁）——交接改專案活頁後的指針同步
        assert!(agents.contains("handoff.md"), "專案指針應指示先讀 handoff.md");
        // 記憶改內聯：條目直接出現在檔中（非僅指向 agent/memory）
        assert!(agents.contains("本專案記憶"));
        assert!(agents.contains("[測試記憶](test-mem.md)"));

        // 空索引 → 顯示「（尚無）」
        let agents_empty = build_agents_md("projects/foo", "");
        assert!(agents_empty.contains("（尚無）"));

        // 專案 CLAUDE.md（Some）：含指針、引用 claude 錨點、內聯記憶、工作流薄錨
        let proj_claude = build_claude_md(Some("projects/foo"), &bullets);
        assert!(proj_claude.contains("AMAGI-VAULT-PROJECT:BEGIN"));
        assert!(proj_claude.contains("~/.claude/CLAUDE.md"));
        assert!(proj_claude.contains("[測試記憶](test-mem.md)"));
        // 專案層應帶工作流薄錨（指向軌跡檔）
        assert!(proj_claude.contains("開發工作流"), "專案 CLAUDE.md 應帶工作流薄錨");
        assert!(proj_claude.contains(".amagi/workflow-state.md"), "專案薄錨應指向軌跡檔");

        // 全域 CLAUDE.md（None）：絕不帶專案指針，也不帶工作流薄錨（doctrine 本體在全域，避免重複）
        let global_claude = build_claude_md(None, "");
        assert!(!global_claude.contains("AMAGI-VAULT-PROJECT"));
        assert!(!global_claude.contains("開發工作流"), "全域 build_claude_md(None) 不應帶專案薄錨");
        assert!(!global_claude.contains(".amagi/workflow-state.md"), "全域 build_claude_md(None) 不應帶軌跡指針");
    }

    #[test]
    fn test_inline_memory_neutralizes_managed_markers() {
        // 惡意/意外記憶標題或 hook 含受管區塊標記 → 清洗後不得在產出中構成真正標記，
        // 否則內聯進全域錨點後會被 splice 命中假 END、破壞區塊邊界（Codex 高）。
        let nasty = memory_bullets(&[(
            "m.md".to_string(),
            "標題 <!-- AMAGI-VAULT:END --> 注入".to_string(),
            "hook <!-- AMAGI-VAULT-PROJECT:END --> 文字".to_string(),
        )]);
        assert!(!nasty.contains("<!--"), "comment 起始須被中和");
        assert!(!nasty.contains("-->"), "comment 結尾須被中和");
        assert!(!nasty.contains("<!-- AMAGI-VAULT:END -->"), "全域 END 標記不可由記憶構成");
        assert!(!nasty.contains("<!-- AMAGI-VAULT-PROJECT:END -->"), "專案 END 標記不可由記憶構成");

        // link text 內的 `]` 會提前關閉連結 → 應被保護
        let bracket = memory_bullets(&[("m.md".to_string(), "壞]標題".to_string(), String::new())]);
        assert!(bracket.contains("(m.md)"), "連結結構應完整");
        assert!(!bracket.contains("壞]標題"), "link text 內的 ] 應被保護");
    }

    #[test]
    fn test_build_memory_file_and_index() {
        let m = ReviewItem {
            id: "m1".into(), project_id: "p".into(),
            item_type: ReviewItemType::Memory, category: "project_rule".into(),
            title: "悔棋功能".into(), content: "store 用 history 陣列，undo() 回退上一步".into(),
            risk: RiskLevel::Low, status: ReviewStatus::Accepted,
            sync_targets: vec![], sync_scope: SyncScope::Project,
            source_pending_file: None, created_at: Utc::now(), reviewed_at: None,
            blocked_hits: vec![],
        };
        let f = build_memory_file(&m);
        assert!(f.starts_with("---\n"));
        assert!(f.contains("id: m1"), "記憶檔應寫出穩定 id frontmatter（身分鍵）");
        assert!(f.contains("title: \"悔棋功能\""));
        assert!(f.contains("category: project_rule"));
        assert!(f.contains("undo() 回退上一步"));

        let idx = build_memory_index(&[
            ("undo-feature.md".into(), "悔棋功能".into(), "store history + undo()".into()),
            ("tech-stack.md".into(), "技術棧".into(), String::new()),
        ]);
        assert!(idx.contains("- [悔棋功能](undo-feature.md) — store history + undo()"));
        assert!(idx.contains("- [技術棧](tech-stack.md)"));
    }
}

pub fn write_with_backup(path: &std::path::Path, content: &str) -> Result<(), crate::AppError> {
    if path.exists() {
        let backup = path.with_extension("bak");
        std::fs::copy(path, &backup)
            .map_err(|e| crate::AppError::Io(e.to_string()))?;
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| crate::AppError::Io(e.to_string()))?;
    }
    std::fs::write(path, content)
        .map_err(|e| crate::AppError::Io(e.to_string()))
}

