use crate::models::review::{ReviewItem, ReviewItemType};

pub fn build_agents_md(items: &[ReviewItem]) -> String {
    let mut lines = vec![
        "# AGENTS.md".to_string(),
        String::new(),
        "> Auto-generated by AMAGI Core. Do not edit manually.".to_string(),
        String::new(),
    ];

    let mut categories: std::collections::BTreeMap<String, Vec<&ReviewItem>> = std::collections::BTreeMap::new();
    for item in items {
        if item.item_type == ReviewItemType::Memory {
            categories.entry(item.category.clone()).or_default().push(item);
        }
    }

    for (category, items) in &categories {
        let heading = category_heading(category);
        lines.push(format!("## {}", heading));
        lines.push(String::new());
        for item in items {
            lines.push(format!("- **{}**: {}", item.title, item.content));
        }
        lines.push(String::new());
    }

    lines.join("\n")
}

pub fn build_claude_md(items: &[ReviewItem]) -> String {
    let mut lines = vec![
        "# CLAUDE.md".to_string(),
        String::new(),
        "> Auto-generated by AMAGI Core. Do not edit manually.".to_string(),
        String::new(),
    ];

    for item in items {
        if item.item_type == ReviewItemType::Memory && item.category == "agent_rule" {
            lines.push(format!("## {}", item.title));
            lines.push(String::new());
            lines.push(item.content.clone());
            lines.push(String::new());
        }
    }

    lines.join("\n")
}

pub fn build_skill_md(item: &ReviewItem) -> String {
    let slug = crate::utils::fs_utils::slugify(&item.title);
    format!(
        "---\nname: {}\ndescription: {}\n---\n\n# {}\n\n{}\n",
        slug, item.title, item.title, item.content
    )
}

pub fn build_claude_command_md(item: &ReviewItem) -> String {
    format!("# {}\n\n{}\n", item.title, item.content)
}

pub fn write_with_backup(path: &std::path::Path, content: &str) -> Result<(), crate::AppError> {
    if path.exists() {
        let backup = path.with_extension("bak");
        std::fs::copy(path, &backup)
            .map_err(|e| crate::AppError::Io(e.to_string()))?;
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| crate::AppError::Io(e.to_string()))?;
    }
    std::fs::write(path, content)
        .map_err(|e| crate::AppError::Io(e.to_string()))
}

fn category_heading(category: &str) -> &str {
    match category {
        "project_rule" => "Project Rules",
        "tech_stack" => "Tech Stack",
        "ci_cd_workflow" => "CI/CD Workflows",
        "tauri_config" => "Tauri Configuration",
        "agent_rule" => "Agent Preferences",
        _ => category,
    }
}
